/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.IambackofficeUserRegistration;
import org.openapitools.client.model.IambackofficeUserTwoFactorConfiguration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeUser
 */
public class IambackofficeUserTest {
    private final IambackofficeUser model = new IambackofficeUser();

    /**
     * Model tests for IambackofficeUser
     */
    @Test
    public void testIambackofficeUser() {
        // TODO: test IambackofficeUser
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'insertInstant'
     */
    @Test
    public void insertInstantTest() {
        // TODO: test insertInstant
    }

    /**
     * Test the property 'lastLoginInstant'
     */
    @Test
    public void lastLoginInstantTest() {
        // TODO: test lastLoginInstant
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'lastUpdateInstant'
     */
    @Test
    public void lastUpdateInstantTest() {
        // TODO: test lastUpdateInstant
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'passwordChangeRequired'
     */
    @Test
    public void passwordChangeRequiredTest() {
        // TODO: test passwordChangeRequired
    }

    /**
     * Test the property 'passwordLastUpdateInstant'
     */
    @Test
    public void passwordLastUpdateInstantTest() {
        // TODO: test passwordLastUpdateInstant
    }

    /**
     * Test the property 'preferredLanguages'
     */
    @Test
    public void preferredLanguagesTest() {
        // TODO: test preferredLanguages
    }

    /**
     * Test the property 'registrations'
     */
    @Test
    public void registrationsTest() {
        // TODO: test registrations
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'twoFactor'
     */
    @Test
    public void twoFactorTest() {
        // TODO: test twoFactor
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

}
