/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IambackofficeUser;
import org.openapitools.client.model.IambackofficeUserRegistration;
import org.openapitools.client.model.ProtobufAny;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeRegistrationResponse
 */
public class IambackofficeRegistrationResponseTest {
    private final IambackofficeRegistrationResponse model = new IambackofficeRegistrationResponse();

    /**
     * Model tests for IambackofficeRegistrationResponse
     */
    @Test
    public void testIambackofficeRegistrationResponse() {
        // TODO: test IambackofficeRegistrationResponse
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

    /**
     * Test the property 'registration'
     */
    @Test
    public void registrationTest() {
        // TODO: test registration
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
