/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProtobufAny;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeLogoutRequest
 */
public class IambackofficeLogoutRequestTest {
    private final IambackofficeLogoutRequest model = new IambackofficeLogoutRequest();

    /**
     * Model tests for IambackofficeLogoutRequest
     */
    @Test
    public void testIambackofficeLogoutRequest() {
        // TODO: test IambackofficeLogoutRequest
    }

    /**
     * Test the property 'global'
     */
    @Test
    public void globalTest() {
        // TODO: test global
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

}
