/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IambackofficeAuthenticatorConfiguration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeTwoFactorMethod
 */
public class IambackofficeTwoFactorMethodTest {
    private final IambackofficeTwoFactorMethod model = new IambackofficeTwoFactorMethod();

    /**
     * Model tests for IambackofficeTwoFactorMethod
     */
    @Test
    public void testIambackofficeTwoFactorMethod() {
        // TODO: test IambackofficeTwoFactorMethod
    }

    /**
     * Test the property 'authenticator'
     */
    @Test
    public void authenticatorTest() {
        // TODO: test authenticator
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

}
