/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IambackofficeTwoFactorMethod;
import org.openapitools.client.model.IambackofficeUser;
import org.openapitools.client.model.ProtobufAny;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeLoginResponse
 */
public class IambackofficeLoginResponseTest {
    private final IambackofficeLoginResponse model = new IambackofficeLoginResponse();

    /**
     * Model tests for IambackofficeLoginResponse
     */
    @Test
    public void testIambackofficeLoginResponse() {
        // TODO: test IambackofficeLoginResponse
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'methods'
     */
    @Test
    public void methodsTest() {
        // TODO: test methods
    }

    /**
     * Test the property 'twoFactorId'
     */
    @Test
    public void twoFactorIdTest() {
        // TODO: test twoFactorId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

}
