/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IambackofficeTwoFactorMethod;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeUserTwoFactorConfiguration
 */
public class IambackofficeUserTwoFactorConfigurationTest {
    private final IambackofficeUserTwoFactorConfiguration model = new IambackofficeUserTwoFactorConfiguration();

    /**
     * Model tests for IambackofficeUserTwoFactorConfiguration
     */
    @Test
    public void testIambackofficeUserTwoFactorConfiguration() {
        // TODO: test IambackofficeUserTwoFactorConfiguration
    }

    /**
     * Test the property 'methods'
     */
    @Test
    public void methodsTest() {
        // TODO: test methods
    }

    /**
     * Test the property 'recoveryCodes'
     */
    @Test
    public void recoveryCodesTest() {
        // TODO: test recoveryCodes
    }

}
