/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IambackofficeUser;
import org.openapitools.client.model.IambackofficeUserRegistration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IambackofficeRegistrationRequest
 */
public class IambackofficeRegistrationRequestTest {
    private final IambackofficeRegistrationRequest model = new IambackofficeRegistrationRequest();

    /**
     * Model tests for IambackofficeRegistrationRequest
     */
    @Test
    public void testIambackofficeRegistrationRequest() {
        // TODO: test IambackofficeRegistrationRequest
    }

    /**
     * Test the property 'registration'
     */
    @Test
    public void registrationTest() {
        // TODO: test registration
    }

    /**
     * Test the property 'sendSetPasswordEmail'
     */
    @Test
    public void sendSetPasswordEmailTest() {
        // TODO: test sendSetPasswordEmail
    }

    /**
     * Test the property 'skipRegistrationVerification'
     */
    @Test
    public void skipRegistrationVerificationTest() {
        // TODO: test skipRegistrationVerification
    }

    /**
     * Test the property 'skipVerification'
     */
    @Test
    public void skipVerificationTest() {
        // TODO: test skipVerification
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

}
