/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IambackofficeUser;
import org.openapitools.client.model.IambackofficeUserRegistration;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Iambackoffice.JSON;

/**
 * IambackofficeRegistrationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-01T08:49:46.493097480Z[Etc/UTC]")
public class IambackofficeRegistrationRequest {
  public static final String SERIALIZED_NAME_REGISTRATION = "registration";
  @SerializedName(SERIALIZED_NAME_REGISTRATION)
  private IambackofficeUserRegistration registration;

  public static final String SERIALIZED_NAME_SEND_SET_PASSWORD_EMAIL = "sendSetPasswordEmail";
  @SerializedName(SERIALIZED_NAME_SEND_SET_PASSWORD_EMAIL)
  private Boolean sendSetPasswordEmail;

  public static final String SERIALIZED_NAME_SKIP_REGISTRATION_VERIFICATION = "skipRegistrationVerification";
  @SerializedName(SERIALIZED_NAME_SKIP_REGISTRATION_VERIFICATION)
  private Boolean skipRegistrationVerification;

  public static final String SERIALIZED_NAME_SKIP_VERIFICATION = "skipVerification";
  @SerializedName(SERIALIZED_NAME_SKIP_VERIFICATION)
  private Boolean skipVerification;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private IambackofficeUser user;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public IambackofficeRegistrationRequest() {
  }

  public IambackofficeRegistrationRequest registration(IambackofficeUserRegistration registration) {
    this.registration = registration;
    return this;
  }

   /**
   * Get registration
   * @return registration
  **/
  @javax.annotation.Nullable
  public IambackofficeUserRegistration getRegistration() {
    return registration;
  }

  public void setRegistration(IambackofficeUserRegistration registration) {
    this.registration = registration;
  }


  public IambackofficeRegistrationRequest sendSetPasswordEmail(Boolean sendSetPasswordEmail) {
    this.sendSetPasswordEmail = sendSetPasswordEmail;
    return this;
  }

   /**
   * Get sendSetPasswordEmail
   * @return sendSetPasswordEmail
  **/
  @javax.annotation.Nullable
  public Boolean getSendSetPasswordEmail() {
    return sendSetPasswordEmail;
  }

  public void setSendSetPasswordEmail(Boolean sendSetPasswordEmail) {
    this.sendSetPasswordEmail = sendSetPasswordEmail;
  }


  public IambackofficeRegistrationRequest skipRegistrationVerification(Boolean skipRegistrationVerification) {
    this.skipRegistrationVerification = skipRegistrationVerification;
    return this;
  }

   /**
   * Get skipRegistrationVerification
   * @return skipRegistrationVerification
  **/
  @javax.annotation.Nullable
  public Boolean getSkipRegistrationVerification() {
    return skipRegistrationVerification;
  }

  public void setSkipRegistrationVerification(Boolean skipRegistrationVerification) {
    this.skipRegistrationVerification = skipRegistrationVerification;
  }


  public IambackofficeRegistrationRequest skipVerification(Boolean skipVerification) {
    this.skipVerification = skipVerification;
    return this;
  }

   /**
   * Get skipVerification
   * @return skipVerification
  **/
  @javax.annotation.Nullable
  public Boolean getSkipVerification() {
    return skipVerification;
  }

  public void setSkipVerification(Boolean skipVerification) {
    this.skipVerification = skipVerification;
  }


  public IambackofficeRegistrationRequest user(IambackofficeUser user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  public IambackofficeUser getUser() {
    return user;
  }

  public void setUser(IambackofficeUser user) {
    this.user = user;
  }


  public IambackofficeRegistrationRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IambackofficeRegistrationRequest iambackofficeRegistrationRequest = (IambackofficeRegistrationRequest) o;
    return Objects.equals(this.registration, iambackofficeRegistrationRequest.registration) &&
        Objects.equals(this.sendSetPasswordEmail, iambackofficeRegistrationRequest.sendSetPasswordEmail) &&
        Objects.equals(this.skipRegistrationVerification, iambackofficeRegistrationRequest.skipRegistrationVerification) &&
        Objects.equals(this.skipVerification, iambackofficeRegistrationRequest.skipVerification) &&
        Objects.equals(this.user, iambackofficeRegistrationRequest.user) &&
        Objects.equals(this.tenantId, iambackofficeRegistrationRequest.tenantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registration, sendSetPasswordEmail, skipRegistrationVerification, skipVerification, user, tenantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IambackofficeRegistrationRequest {\n");
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("    sendSetPasswordEmail: ").append(toIndentedString(sendSetPasswordEmail)).append("\n");
    sb.append("    skipRegistrationVerification: ").append(toIndentedString(skipRegistrationVerification)).append("\n");
    sb.append("    skipVerification: ").append(toIndentedString(skipVerification)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("registration");
    openapiFields.add("sendSetPasswordEmail");
    openapiFields.add("skipRegistrationVerification");
    openapiFields.add("skipVerification");
    openapiFields.add("user");
    openapiFields.add("tenantId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to IambackofficeRegistrationRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IambackofficeRegistrationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IambackofficeRegistrationRequest is not found in the empty JSON string", IambackofficeRegistrationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IambackofficeRegistrationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IambackofficeRegistrationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `registration`
      if (jsonObj.get("registration") != null && !jsonObj.get("registration").isJsonNull()) {
        IambackofficeUserRegistration.validateJsonElement(jsonObj.get("registration"));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        IambackofficeUser.validateJsonElement(jsonObj.get("user"));
      }
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IambackofficeRegistrationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IambackofficeRegistrationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IambackofficeRegistrationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IambackofficeRegistrationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<IambackofficeRegistrationRequest>() {
           @Override
           public void write(JsonWriter out, IambackofficeRegistrationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IambackofficeRegistrationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IambackofficeRegistrationRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IambackofficeRegistrationRequest
  * @throws IOException if the JSON string is invalid with respect to IambackofficeRegistrationRequest
  */
  public static IambackofficeRegistrationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IambackofficeRegistrationRequest.class);
  }

 /**
  * Convert an instance of IambackofficeRegistrationRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

