/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Iambackoffice.JSON;

/**
 * IambackofficeAuthenticatorConfiguration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T12:00:48.087044450Z[Etc/UTC]")
public class IambackofficeAuthenticatorConfiguration {
  public static final String SERIALIZED_NAME_ALGORITHM = "algorithm";
  @SerializedName(SERIALIZED_NAME_ALGORITHM)
  private String algorithm;

  public static final String SERIALIZED_NAME_CODE_LENGTH = "codeLength";
  @SerializedName(SERIALIZED_NAME_CODE_LENGTH)
  private Integer codeLength;

  public static final String SERIALIZED_NAME_TIME_STEP = "timeStep";
  @SerializedName(SERIALIZED_NAME_TIME_STEP)
  private Integer timeStep;

  public IambackofficeAuthenticatorConfiguration() {
  }

  public IambackofficeAuthenticatorConfiguration algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @javax.annotation.Nullable
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }


  public IambackofficeAuthenticatorConfiguration codeLength(Integer codeLength) {
    this.codeLength = codeLength;
    return this;
  }

   /**
   * Get codeLength
   * @return codeLength
  **/
  @javax.annotation.Nullable
  public Integer getCodeLength() {
    return codeLength;
  }

  public void setCodeLength(Integer codeLength) {
    this.codeLength = codeLength;
  }


  public IambackofficeAuthenticatorConfiguration timeStep(Integer timeStep) {
    this.timeStep = timeStep;
    return this;
  }

   /**
   * Get timeStep
   * @return timeStep
  **/
  @javax.annotation.Nullable
  public Integer getTimeStep() {
    return timeStep;
  }

  public void setTimeStep(Integer timeStep) {
    this.timeStep = timeStep;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IambackofficeAuthenticatorConfiguration iambackofficeAuthenticatorConfiguration = (IambackofficeAuthenticatorConfiguration) o;
    return Objects.equals(this.algorithm, iambackofficeAuthenticatorConfiguration.algorithm) &&
        Objects.equals(this.codeLength, iambackofficeAuthenticatorConfiguration.codeLength) &&
        Objects.equals(this.timeStep, iambackofficeAuthenticatorConfiguration.timeStep);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, codeLength, timeStep);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IambackofficeAuthenticatorConfiguration {\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    codeLength: ").append(toIndentedString(codeLength)).append("\n");
    sb.append("    timeStep: ").append(toIndentedString(timeStep)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("algorithm");
    openapiFields.add("codeLength");
    openapiFields.add("timeStep");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to IambackofficeAuthenticatorConfiguration
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IambackofficeAuthenticatorConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IambackofficeAuthenticatorConfiguration is not found in the empty JSON string", IambackofficeAuthenticatorConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IambackofficeAuthenticatorConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IambackofficeAuthenticatorConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("algorithm") != null && !jsonObj.get("algorithm").isJsonNull()) && !jsonObj.get("algorithm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `algorithm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("algorithm").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IambackofficeAuthenticatorConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IambackofficeAuthenticatorConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IambackofficeAuthenticatorConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IambackofficeAuthenticatorConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<IambackofficeAuthenticatorConfiguration>() {
           @Override
           public void write(JsonWriter out, IambackofficeAuthenticatorConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IambackofficeAuthenticatorConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IambackofficeAuthenticatorConfiguration given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IambackofficeAuthenticatorConfiguration
  * @throws IOException if the JSON string is invalid with respect to IambackofficeAuthenticatorConfiguration
  */
  public static IambackofficeAuthenticatorConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IambackofficeAuthenticatorConfiguration.class);
  }

 /**
  * Convert an instance of IambackofficeAuthenticatorConfiguration to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

