/*
 * IamBackoffice Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.IambackofficeMetaData;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Iambackoffice.JSON;

/**
 * IambackofficeLoginRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T12:00:48.087044450Z[Etc/UTC]")
public class IambackofficeLoginRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ipAddress";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  private String ipAddress;

  public static final String SERIALIZED_NAME_LOGIN_ID = "loginId";
  @SerializedName(SERIALIZED_NAME_LOGIN_ID)
  private String loginId;

  public static final String SERIALIZED_NAME_META_DATA = "metaData";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  private IambackofficeMetaData metaData;

  public static final String SERIALIZED_NAME_NO_TOKENS = "noTokens";
  @SerializedName(SERIALIZED_NAME_NO_TOKENS)
  private Boolean noTokens;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_TWO_FACTOR_TRUST_ID = "twoFactorTrustId";
  @SerializedName(SERIALIZED_NAME_TWO_FACTOR_TRUST_ID)
  private String twoFactorTrustId;

  public IambackofficeLoginRequest() {
  }

  public IambackofficeLoginRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public IambackofficeLoginRequest ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @javax.annotation.Nullable
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }


  public IambackofficeLoginRequest loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

   /**
   * Get loginId
   * @return loginId
  **/
  @javax.annotation.Nullable
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }


  public IambackofficeLoginRequest metaData(IambackofficeMetaData metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @javax.annotation.Nullable
  public IambackofficeMetaData getMetaData() {
    return metaData;
  }

  public void setMetaData(IambackofficeMetaData metaData) {
    this.metaData = metaData;
  }


  public IambackofficeLoginRequest noTokens(Boolean noTokens) {
    this.noTokens = noTokens;
    return this;
  }

   /**
   * Get noTokens
   * @return noTokens
  **/
  @javax.annotation.Nullable
  public Boolean getNoTokens() {
    return noTokens;
  }

  public void setNoTokens(Boolean noTokens) {
    this.noTokens = noTokens;
  }


  public IambackofficeLoginRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }


  public IambackofficeLoginRequest twoFactorTrustId(String twoFactorTrustId) {
    this.twoFactorTrustId = twoFactorTrustId;
    return this;
  }

   /**
   * Get twoFactorTrustId
   * @return twoFactorTrustId
  **/
  @javax.annotation.Nullable
  public String getTwoFactorTrustId() {
    return twoFactorTrustId;
  }

  public void setTwoFactorTrustId(String twoFactorTrustId) {
    this.twoFactorTrustId = twoFactorTrustId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IambackofficeLoginRequest iambackofficeLoginRequest = (IambackofficeLoginRequest) o;
    return Objects.equals(this.tenantId, iambackofficeLoginRequest.tenantId) &&
        Objects.equals(this.ipAddress, iambackofficeLoginRequest.ipAddress) &&
        Objects.equals(this.loginId, iambackofficeLoginRequest.loginId) &&
        Objects.equals(this.metaData, iambackofficeLoginRequest.metaData) &&
        Objects.equals(this.noTokens, iambackofficeLoginRequest.noTokens) &&
        Objects.equals(this.password, iambackofficeLoginRequest.password) &&
        Objects.equals(this.twoFactorTrustId, iambackofficeLoginRequest.twoFactorTrustId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, ipAddress, loginId, metaData, noTokens, password, twoFactorTrustId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IambackofficeLoginRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    noTokens: ").append(toIndentedString(noTokens)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    twoFactorTrustId: ").append(toIndentedString(twoFactorTrustId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("ipAddress");
    openapiFields.add("loginId");
    openapiFields.add("metaData");
    openapiFields.add("noTokens");
    openapiFields.add("password");
    openapiFields.add("twoFactorTrustId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to IambackofficeLoginRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IambackofficeLoginRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IambackofficeLoginRequest is not found in the empty JSON string", IambackofficeLoginRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IambackofficeLoginRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IambackofficeLoginRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if ((jsonObj.get("ipAddress") != null && !jsonObj.get("ipAddress").isJsonNull()) && !jsonObj.get("ipAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ipAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipAddress").toString()));
      }
      if ((jsonObj.get("loginId") != null && !jsonObj.get("loginId").isJsonNull()) && !jsonObj.get("loginId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `loginId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("loginId").toString()));
      }
      // validate the optional field `metaData`
      if (jsonObj.get("metaData") != null && !jsonObj.get("metaData").isJsonNull()) {
        IambackofficeMetaData.validateJsonElement(jsonObj.get("metaData"));
      }
      if ((jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) && !jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
      if ((jsonObj.get("twoFactorTrustId") != null && !jsonObj.get("twoFactorTrustId").isJsonNull()) && !jsonObj.get("twoFactorTrustId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `twoFactorTrustId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("twoFactorTrustId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IambackofficeLoginRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IambackofficeLoginRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IambackofficeLoginRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IambackofficeLoginRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<IambackofficeLoginRequest>() {
           @Override
           public void write(JsonWriter out, IambackofficeLoginRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IambackofficeLoginRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IambackofficeLoginRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IambackofficeLoginRequest
  * @throws IOException if the JSON string is invalid with respect to IambackofficeLoginRequest
  */
  public static IambackofficeLoginRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IambackofficeLoginRequest.class);
  }

 /**
  * Convert an instance of IambackofficeLoginRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

